import type { Metadata } from "next";
import localFont from 'next/font/local'
import {Michroma} from 'next/font/google'
import { Header } from "@/app/components/Header";
import { Footer } from "@/app/components/Footer";
import "./globals.css";

const michromaFont = Michroma({
  weight:['400'],
  subsets:['latin'],
})

const euroStileFont = localFont({
  src: [
    {
      path: '../fonts/fonnts.com-Eurostile_Extd_Black.otf',
      weight: '900',
      style: 'normal',
    }
  ],
  variable:'--font-eurostile'
})

const generalSansFont = localFont({
  src:[
    { 
      path:'../fonts/GeneralSans-Medium.otf',
      weight:'400',
      style: 'normal'
    },
    { 
      path:'../fonts/GeneralSans-MediumItalic.otf',
      weight:'400',
      style: 'italic'
    },
    { 
      path:'../fonts/GeneralSans-Semibold_2.otf',
      weight:'700',
      style: 'normal'
    },
  ],
  variable:'--font-general-sans'
})

export const metadata: Metadata = {
  title: "Pure Detail",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${generalSansFont.variable} ${euroStileFont.className} antialiased bg-black text-white`}>
        <Header/>
        <main>
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
